spot_prices:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: sensor
          integration: ostrom
    resolution:
      required: true
      selector:
        select:
          options:
            - value: hourly
              label: Hourly
            - value: monthly
              label: Monthly
